server:
  port: 8083

zuul:
  prefix: /api
  routes:
    multiplications:
      path: /multiplications/**
      url: http://localhost:8085/multiplications
    results:
      path: /results/**
      url: http://localhost:8085/results
    leaders:
      path: /leaders/**
      url: http://localhost:8086/leaders
    stats: /stats/**
      path:
      url: http://localhost:8086/stats

endpoint:
  trace:
    sensitive: false

ribbon:
  eureka:
    enabled: false
